name: Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Login and Execute Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd quizbot/quizpal/
            rm actions.log
            git stash
            git checkout
            git pull
            /home/${{ secrets.SERVER_USERNAME }}/.local/bin/poetry shell
            /home/${{ secrets.SERVER_USERNAME }}/.local/bin/poetry install --no-root
            /home/${{ secrets.SERVER_USERNAME }}/.local/bin/poetry run playwright install
            /home/${{ secrets.SERVER_USERNAME }}/.local/bin/poetry run pw_migrate migrate --database sqlite:/databases/bot.db --directory src/migrations >> actions.log 2>&1
            sudo systemctl restart quizbot.service >> actions.log 2>&1
            OUTPUT=$(cat actions.log)
            curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
                        -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
                        -d "text=%0A\`\`\`Server%0Acommit%0A%0A${{ github.event.head_commit.message }}%0ALog%0A%0A${OUTPUT}%0A\`\`\`" \
                        -d "parse_mode=MarkdownV2"